/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/AirplaneOld.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const AirplaneOld = (props) => {
  const { nodes, materials } = useGLTF('/models/AirplaneOld.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.PUSHILIN_Plane_Circle000.geometry}>
        <meshStandardMaterial color="white" />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/AirplaneOld.glb')

export default AirplaneOld