/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/cloud.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { fadeOnBeforeCompile } from '../utils/fadeMaterial'

const Cloud = ({opacity, ...props}) => {
  const { nodes, materials } = useGLTF('/models/cloud.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mball001.geometry}>
        <meshStandardMaterial 
          envMapIntensity={2}
          transparent
          opacity={opacity}  
          onBeforeCompile={fadeOnBeforeCompile}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/cloud.gltf')

export default Cloud